name: Deploy to GitHub Pages

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    uses: dale25519/dale25519.github.io/.github/workflows/pnpm-gh-pages.yml@master
    with:
      publish_dir: build
